# Generated by Django 4.0.6 on 2022-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
