# Generated by Django 4.0.6 on 2022-08-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='main_content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='journalist',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='press',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newsimage'),
        ),
    ]
