# Generated by Django 4.0.5 on 2022-08-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
