# Generated by Django 4.0.5 on 2022-08-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='collection',
        ),
    ]
