# Generated by Django 4.0.6 on 2022-08-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_name_collection_title'),
        ('post', '0002_alter_folder_parentfolder_alter_post_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
    ]
