# Generated by Django 4.0.5 on 2022-08-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0001_initial'),
        ('post', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='post',
            name='refCount',
            field=models.IntegerField(default=0, verbose_name='참조수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection', verbose_name='참조 컬렉션'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(null=True, verbose_name='인사이트 대표 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='좋아요수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
