# Generated by Django 4.0.5 on 2022-08-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comment_num_post_refcount_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
    ]
