# Generated by Django 4.0.5 on 2022-08-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='인사이트 대표 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
