# Generated by Django 4.0.5 on 2022-08-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_folder_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.folder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(default='www.naver.com', verbose_name='인사이트 대표 이미지'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='post.tag'),
        ),
    ]
