# Generated by Django 4.0.5 on 2022-08-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_folder_alter_post_img_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='인사이트 대표 이미지'),
        ),
    ]
