# Generated by Django 4.0.5 on 2022-08-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='comment',
            field=models.CharField(max_length=120, null=True, verbose_name='커멘트'),
        ),
    ]