# Generated by Django 4.0.6 on 2022-08-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tag',
            field=models.ManyToManyField(null=True, to='post.tag'),
        ),
    ]
