# Generated by Django 4.0.5 on 2022-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_collection'),
        ('collection', '0002_collection_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tag',
            field=models.ManyToManyField(to='post.tag'),
        ),
    ]
