# Generated by Django 4.0.6 on 2022-08-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('collection', '0002_rename_name_collection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.tag'),
        ),
    ]
