# Generated by Django 4.0.6 on 2022-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='comment',
            field=models.CharField(max_length=120, null=True, verbose_name='코멘트'),
        ),
    ]
