# Generated by Django 4.0.5 on 2022-08-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_intro'),
        ('collection', '0002_collection_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='comment',
            field=models.CharField(max_length=120, null=True, verbose_name='코멘트'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만든 날짜'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='좋아요수'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='refCount',
            field=models.IntegerField(default=0, verbose_name='참조수'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=120, verbose_name='컬렉션제목'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
