# Generated by Django 4.0.5 on 2022-08-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.CharField(default='정치', max_length=120),
            preserve_default=False,
        ),
    ]