# Generated by Django 4.0.6 on 2022-08-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('collection', '0003_collection_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='tag',
        ),
        migrations.AddField(
            model_name='collection',
            name='tag',
            field=models.ManyToManyField(null=True, to='post.tag'),
        ),
    ]
