# Generated by Django 4.0.5 on 2022-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('collection', '0003_remove_collection_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='news',
            field=models.ManyToManyField(to='news.news'),
        ),
    ]
