# Generated by Django 4.0.5 on 2022-08-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_image'),
        ('collection', '0004_collection_news'),
    ]

    operations = [
    ]
