# Generated by Django 4.0.6 on 2022-08-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_collection_user_collection_author'),
        ('collection', '0004_remove_collection_tag_collection_tag'),
    ]

    operations = [
    ]
