# Generated by Django 4.0.6 on 2022-08-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.CharField(max_length=200, null=True, verbose_name='한줄소개'),
        ),
    ]
