# Generated by Django 4.0.6 on 2022-08-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_collectionscrapped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CollectionScrapped',
            new_name='collectionScrapped',
        ),
    ]
