# Generated by Django 4.0.5 on 2022-08-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
