# Generated by Django 4.0.6 on 2022-08-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_collectionscrapped_user_collectionscrapped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collectionScrapped',
            new_name='collectionScrappeds',
        ),
    ]
