# Generated by Django 4.0.5 on 2022-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_nick_alter_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
