# Generated by Django 4.0.6 on 2022-08-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_collectionscrapped_user_collectionscrappeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collectionScrappeds',
            new_name='collectionScrapped',
        ),
    ]
