# Generated by Django 4.0.6 on 2022-08-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
        ('accounts', '0007_alter_profile_user'),
    ]

    operations = [
    ]
